import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import JotaiProvider from "@/components/providers/jotai";
import URQLProvider from "@/components/providers/urql";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <URQLProvider>
          <JotaiProvider>{children}</JotaiProvider>
        </URQLProvider>
        <Toaster />
      </body>
    </html>
  );
}
