import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import NavLayout from "@/components/layouts/l-nav-layout";
import JotaiProvider from "@/components/providers/jotai";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <JotaiProvider>
          <NavLayout>{children}</NavLayout>
        </JotaiProvider>
      </body>
    </html>
  );
}
